export default interface Recipe {
	idMeal: string,
	strMeal: string,
	strMealThumb: string,
	strInstructions: string,
	strYoutube: string,
	strIngredient1: string,
	strIngredient2: string,
	strIngredient3: string,
	strIngredient4: string,
	strIngredient5: string,
	strIngredient6: string,
	strIngredient7: string,
	strIngredient8: string,
	strIngredient9: string,
	strIngredient10: string,
	strIngredient11: string,
	strIngredient12: string,
}