interface IngredientsMap {
	[key: string]: string[]
}

export const ingredients: IngredientsMap = {
	garlic: ['bg-zinc-500'],
	beef: ['bg-red-700'],
	pepper: ['bg-stone-500'],
	nutmeg: ['bg-yellow-700'],
	cumin: ['bg-yellow-700'],
	tomato: ['bg-red-700'],
	tomato_puree: ['bg-red-700'],
	bacon: ['bg-red-900'],
	potatoes: ['bg-orange-900'],
	sausages: ['bg-amber-700'],
	lentils: ['bg-amber-900'],
	pork: ['bg-orange-900'],
	kale: ['bg-green-800'],
	water: ['bg-blue-700'],
	onion: ['bg-violet-400', 'text-black'],
	carrots: ['bg-orange-500', 'text-black'],
	carrot: ['bg-orange-500', 'text-black'],
	peprika: ['bg-amber-500', 'text-black'],
	paprika: ['bg-amber-500', 'text-black'],
	ghee: ['bg-yellow-400', 'text-black'],
	lemon: ['bg-yellow-500', 'text-black'],
	fries: ['bg-yellow-600', 'text-black'],
	cheese: ['bg-yellow-600', 'text-black'],
	butter: ['bg-yellow-500', 'text-black'],
	egg: ['bg-amber-500', 'text-black'],
	eggs: ['bg-amber-500', 'text-black'],
	milk: ['bg-white', 'text-black'],
	shallots: ['bg-violet-400', 'text-black'],
	sugar: ['bg-white', 'text-black'],
	flour: ['bg-gray-300', 'text-black'],
	salt: ['bg-gray-400', 'text-black'],
	pumpkin: ['bg-orange-500', 'text-black'],
	turmeric: ['bg-orange-400', 'text-black'],
	raspberries: ['bg-rose-500', 'text-black'],
	lettuce: ['bg-green-500', 'text-black'],
	leek: ['bg-green-500', 'text-black'],
	coriander: ['bg-green-500', 'text-black'],
	parsley: ['bg-green-600', 'text-black'],
	celery: ['bg-green-500', 'text-black'],
	parmesan: ['bg-amber-500', 'text-black'],
}